apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-deployment
  labels:
    app.kubernetes.io/name: info
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: info
  template:
    metadata:
      labels:
        app.kubernetes.io/name: info
    spec:
      containers:
      - name: info
        image: armennanayan/book-info:1.0.0
        ports:
        - containerPort: 8081
          name: rest-port
      
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: info
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8081
      targetPort: rest-port
      nodePort: 30102  #This is what we need to poke in goodle cloud