apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app.kubernetes.io/name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front
    spec:
      containers:
      - name: front
        image: armennanayan/my-flask-app:1.0.0
        ports:
        - containerPort: 8084
          name: rest-port 
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: front
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8084
      targetPort: rest-port
      nodePort: 30105  #This is what we need to poke in goodle cloud
